# Generated by Django 5.1.5 on 2025-02-23 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='current_subtopic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_subtopics', to='my_app.subtopic'),
        ),
        migrations.AddField(
            model_name='progress',
            name='next_subtopic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_subtopics', to='my_app.subtopic'),
        ),
        migrations.AddField(
            model_name='progress',
            name='video_watched',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='progress',
            name='current_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_topics', to='my_app.topic'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='next_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_topics', to='my_app.topic'),
        ),
    ]
