# Generated by Django 5.1.5 on 2025-02-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='assigned_at',
            field=models.IntegerField(choices=[(0, 'Before Assignment'), (1, 'After Assignment')], default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='subtopic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
