# Generated by Django 5.1.5 on 2025-03-04 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_progress_current_subtopic_progress_next_subtopic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched', models.BooleanField(default=False)),
                ('watched_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.student')),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.subtopic')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.videomodule')),
            ],
            options={
                'unique_together': {('student', 'video')},
            },
        ),
    ]
