# Generated by Django 5.1.5 on 2025-02-15 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_question_assigned_at_question_subtopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodule',
            name='subtopic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
