# Generated by Django 5.1.5 on 2025-03-04 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_videoprogress'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='progress',
            unique_together={('student', 'module', 'current_subtopic')},
        ),
    ]
