# Generated by Django 5.1.5 on 2025-04-19 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_alter_progress_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodule',
            name='misconceptions',
            field=models.CharField(blank=True, help_text="Comma-separated list of related misconception numbers like 'm1,m2,m5'", max_length=255),
        ),
    ]
