# Generated by Django 5.2 on 2025-05-03 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_videomodule_misconceptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='subtopic',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='my_app.subtopic'),
            preserve_default=False,
        ),
    ]
