# Generated by Django 5.2 on 2025-05-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_experimentassessmentscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='can_take_experimental_test',
            field=models.BooleanField(default=False),
        ),
    ]
