# Generated by Django 5.2.1 on 2025-05-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_student_can_take_experimental_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodule',
            name='embedding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
