# Generated by Django 5.2.1 on 2025-06-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_videomodule_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Misconception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('misconception_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
